-include .env

.PHONY: all test clean deploy fund help install snapshot format anvil 

build:; forge build

deploy: 
	@forge script script/DeployFixie.s.sol --broadcast --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://127.0.0.1:8545